### ISSUE TITLE
XPATH error SOS_ETS.xml

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos10#1]
Testing suite sos:suite in Test Mode with defaultResult of Pass ...
Testing sos:Main type Mandatory in Test Mode with defaultResult Pass (s0012)...
      Assertion: The IUT satisfies all applicable assertions.
Exception in thread "TEAM Engine" java.lang.Exception: Fatal Error: XPath syntax error at char 70 on line 684 in {...ogc.schema.root, $ows.versi...}:
    Cannot find a matching 2-argument function named {https://cite.opengeospatial.org/sos-1.0.0/src/ctl/functions.xml}exceptionReportSchemaPath(); SystemID: file:/Users/lbermudez/teamengine/TE_BASE/work/_Users_lbermudez_teamengine_TE_BASE_scripts_sos_1.0.0_ctl_SOS_ETS.xml/sos$Main.test; Line#: 684; Column#: -1
Failed to compile stylesheet. 1 error detected.
    at com.occamlab.te.Engine.loadExecutable(Engine.java:189)
    at com.occamlab.te.TECore.executeTemplate(TECore.java:498)
    at com.occamlab.te.TECore.executeTest(TECore.java:660)
    at com.occamlab.te.TECore.execute_test(TECore.java:347)
    at com.occamlab.te.TECore.execute_suite(TECore.java:390)
    at com.occamlab.te.TECore.execute(TECore.java:252)
    at com.occamlab.te.Test.main(Test.java:354)
Caused by: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
    at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
    at net.sf.saxon.PreparedStylesheet.compile(PreparedStylesheet.java:79)
    at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:146)
    at com.occamlab.te.Engine.loadExecutable(Engine.java:181)

**Comment by rockygis** [comment]
It seems it cannot link to the "function.xml" file.
The function "exceptionReportSchemaPath" is in the "function.xml" file.

**Comment by bermud** [comment]
v 1.13 is not presetting this issue. Will close.
